saved_models:
  entire_model: data/models/entire_model/
  weights_model: data/models/weights_model/
  chkpoint_model: data/models/chkpoint_model/
  base_chkpoint_model: data/models/base_chkpoint_model/
  gru_chkpoint_model: data/models/base_chkpoint_model/

data:
  history_weather: data/weather/
